#!/bin/bash
# =============================================================================
# onboard-client.sh — Set up a new client in the agent system
#
# Usage: ./scripts/onboard-client.sh <client-slug>
# 
# Creates the full client directory structure and config template.
# Founder fills in the config, then agents can start working.
# =============================================================================

set -euo pipefail

SLUG="${1:?Usage: onboard-client.sh <client-slug>}"
CLIENT_DIR="clients/${SLUG}"

if [ -d "$CLIENT_DIR" ]; then
    echo "Error: Client directory ${CLIENT_DIR} already exists."
    exit 1
fi

echo "📁 Creating client structure for: ${SLUG}"

# Create directories
mkdir -p "${CLIENT_DIR}"/{reports,content,design}

# Create config template
cat > "${CLIENT_DIR}/config.yaml" << 'YAML'
# =============================================================================
# Client Configuration — FILL IN ALL FIELDS
# =============================================================================

name: "BUSINESS NAME HERE"
slug: SLUG_HERE
url: https://example.co.uk
staging_url: https://staging.example.co.uk  # Leave blank if no staging
cms: wordpress  # wordpress | shopify | squarespace | custom | static
cms_version: ""
hosting: ""  # siteground | godaddy | 123-reg | other
plan: standard  # basic | standard | premium

monthly_fee: 500
contract_start: 2025-02-08

contact_name: ""
contact_email: ""
contact_phone: ""

services:  # Which agent services are active for this client
  - maintenance
  # - seo
  # - content
  # - reporting

seo_targets:
  primary_keywords: []
  target_area: "Sheffield"

content_preferences:
  tone: "professional"
  blog_frequency: "1 per month"
  topics_avoid: []
  topics_preferred: []

notes: |
  Add any important notes about this client here.
  Things the agents should know: preferences, sensitivities, competitors, goals.

risk_factors:
  churn_risk: low  # low | medium | high
  last_contact: 2025-02-08
  satisfaction: unknown  # high | medium | low | unknown
  open_issues: 0
YAML

# Replace slug placeholder
sed -i "s/SLUG_HERE/${SLUG}/" "${CLIENT_DIR}/config.yaml"

# Create health log
cat > "${CLIENT_DIR}/health-log.md" << EOF
# Health Log — ${SLUG}

*Auto-generated by maintenance agent. Manual entries welcome.*

EOF

# Create README
cat > "${CLIENT_DIR}/README.md" << EOF
# ${SLUG}

## Setup Checklist
- [ ] Fill in config.yaml with all client details
- [ ] Set up staging environment URL
- [ ] Add CMS login credentials to password manager (NOT in config.yaml)
- [ ] Run initial health check: \`./scripts/health-check.sh --client ${SLUG}\`
- [ ] Run initial QA audit: \`./scripts/run-agent.sh qa "Full initial audit" --client ${SLUG}\`
- [ ] Run initial SEO baseline: \`./scripts/run-agent.sh seo "Initial SEO baseline" --client ${SLUG}\`
- [ ] Brief agents on client preferences and priorities

## Quick Commands
\`\`\`bash
# Health check
./scripts/health-check.sh --client ${SLUG}

# Run maintenance
./scripts/run-agent.sh maintenance "Weekly maintenance check" --client ${SLUG}

# Run QA audit
./scripts/run-agent.sh qa "Full site audit" --client ${SLUG}

# Draft content
./scripts/run-agent.sh content "Draft blog post about [topic]" --client ${SLUG}

# SEO report
./scripts/run-agent.sh seo "Monthly SEO report" --client ${SLUG}

# Generate client report
./scripts/run-agent.sh reports "Monthly client report" --client ${SLUG}
\`\`\`
EOF

echo ""
echo "✅ Client '${SLUG}' created at ${CLIENT_DIR}/"
echo ""
echo "📋 Next steps:"
echo "  1. Edit ${CLIENT_DIR}/config.yaml with client details"
echo "  2. Store credentials in your password manager (NEVER in config files)"
echo "  3. Run initial health check and audits"
echo "  4. Add client to daily orchestration"
echo ""
